description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine
parameters:
  image:
    type: string
    default: ubuntu-2004:202107-02
  use-docker-layer-caching:
    type: boolean
    default: false
  resource-class:
    type: string
    default: medium

machine:
  image: <<parameters.image>>
  docker_layer_caching: <<parameters.use-docker-layer-caching>>

resource_class: <<parameters.resource-class>>
