description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine
parameters:
  image:
    type: string
    default: ubuntu-2204:current
  docker_layer_caching:
    type: boolean
    default: false
  resource_class:
    type: string
    default: medium

machine:
  image: <<parameters.image>>
  docker_layer_caching: <<parameters.docker_layer_caching>>

resource_class: <<parameters.resource_class>>
