version: 2.1

description: |
  An orb for working with Amazon Elastic Container Registry (ECR)
  Sample usage within config.yml:

  workflows:
    build_and_push_image:
      jobs:
        - aws-ecr/build_and_push_image:
            context: myContext
            region: us-west-2
            account-url: myAwsAccountNum.dkr.ecr.myRegion.amazonaws.com 
            repo: myRepo
            tag: latest

  The executors within this Orb provide run-time environments that contain the 
  necessary dependencies for executing the jobs and commands in this orb. 
  Required dependencies - docker.

orbs:
  aws-cli: ttrahan/aws-cli@dev:alpha

executors:
  default:
    docker:
      - image: circleci/python:3-stretch-browsers

commands:
  ecr-login:
    description: "Authenticate into the Amazon ECR service"
    parameters: 
      region: 
        type: string
        default: "us-east-1"
    steps:
      - run:
          name: Log into Amazon ECR
          command: "$(aws ecr get-login --no-include-email --region <<parameters.region>> )"
  build-image:
    description: "Build a docker image"
    parameters:
      account-url:
        type: string
        description: A directory path local to the job to deploy to S3
      repo:
        type: string
        description: A URI to an Amazon ECR repository
      tag:
        default: "latest"
        type: string
    steps:
      - run:
          name: Build docker image
          command: "docker build -t <<parameters.account-url>>/<<parameters.repo>>:<<parameters.tag>> ."
  push-image:
    description: "Push a container image to the Amazon ECR registry"
    parameters:
      account-url:
        type: string
        description: A directory path local to the job to deploy to S3
      repo:
        type: string
        description: A URI to an Amazon ECR repository
      tag:
        default: "latest"
        type: string
    steps:
      - run:
          name: Push image to Amazon ECR
          command: "docker push <<parameters.account-url>>/<<parameters.repo>>:<<parameters.tag>>"

jobs:
  build_and_push_image:
    description: Install AWS CLI, if needed, and configure. Log into Amazon ECR
                 and push image to repository. Requires environment variables 
                 for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. We recommend
                 these be saved in a Project (https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project) or in 
                 Contexts (https://circleci.com/docs/2.0/contexts/).
    executor: default
    parameters: 
      profile-name:
        description: AWS profile name to be configured.
        type: string
        default: "default"
      aws-access-key-id:
        description: AWS access key id for IAM role. Set this to the name of
                     the environment variable you will set to hold this
                     value, i.e. $AWS_ACCESS_KEY.
        type: string
        default: $AWS_ACCESS_KEY_ID
      aws-secret-access-key:
        description: AWS secret key for IAM role. Set this to the name of
                     the environment variable you will set to hold this
                     value, i.e. $AWS_SECRET_ACCESS_KEY.
        type: string
        default: $AWS_SECRET_ACCESS_KEY
      region: 
        type: string
        description: AWS region to use with the commands (default = us-east-1)
        default: "us-east-1"
      account-url:
        type: string
        description: A directory path local to the job to deploy to S3
      repo:
        type: string
        description: A URI to an Amazon ECR repository
      tag:
        type: string
        description: Docker tag (default = latest)
        default: "latest"
    steps:
      - aws-cli/install
      - aws-cli/configure: 
          profile-name: << parameters.profile-name >>
          aws-access-key-id: << parameters.aws-access-key-id >>
          aws-secret-access-key: << parameters.aws-secret-access-key >>
          region: << parameters.region >>
      - checkout
      - setup_remote_docker
      - ecr-login:
          region: << parameters.region >>
      - build-image:
          account-url: << parameters.account-url >>
          repo: << parameters.repo >>
          tag: << parameters.tag >> 
      - push-image:
          account-url: << parameters.account-url >>
          repo: << parameters.repo >>
          tag: << parameters.tag >> 
